### ISSUE TITLE
mysql-wsrep package name?

### ISSUE THREAD

**Issue by dvandok** [salt-formulas/salt-formula-galera#32]
I'm using the Mirantis openstack repo http://mirror.fuel-infra.org/mos-repos/ubuntu/9.0 and the package name is different from what it says in map.jinja: mysql-server-wsrep-5.6 rather than mysql-wsrep-5.6.

Is this a transitional issue?

**Comment by Lirt** [comment]
Hi, I was testing this formula with `test-kitchen` and `ubuntu 16.04` today and found several issues with repositories. 

First of all the repository for galera changed its structure. and we need to use these following URLs in tests.

```bash
http://releases.galeracluster.com/galera-3
http://releases.galeracluster.com/wsrep-5.6 or http://releases.galeracluster.com/wsrep-5.7
```

Second issue is that package `python-mysqldb` installs as dependency `libmysqlclient20` and `mysql-common 5.7` which conflicts with `wsrep-5.6` and all other packages with version 5.6.

Third issue was missing `key_ids` for test repositories.

**Comment by Martin819** [comment]
The package name is now _mysql-wsrep-5.6_

**Comment by dvandok** [comment]
ok, that's cleared up then.
